### ISSUE TITLE
MathJax integration does not properly escape {}

### ISSUE THREAD

**Issue by mariari** [melisgl/mgl-pax#17]
when trying to write code with MathJax it seems that mgl-pax does not properly allow curlybrace escape. For example code like:

```lisp
(pax:defsection @math-playground (:title "math-playground")
  """
$\mathsf{3} = \\{ 1, 2, 3 \\}$

$\mathsf{3} = \{ 1, 2, 3 \}$

$$\mathsf{3} = \{ 1, 2, 3 \}$$
""")
```

displays like https://pomf2.lain.la/f/km9lm4sq.png however it should display the curly braces as they are properly escaped.

EDIT :: 
After some digging, it seems that `\lbrace` and `\rbrace` work, however it would be good to add this to the documentation in the mathjax's section

**Comment by melisgl** [comment]
The problem here is the "\\{" (lisp string with one backslash) is parsed to "{" by 3bmd, and when markdown is generated { is not escaped. Thus parse/print consistency is lost.
I updated a related pull request in 3bmd to include {} characters, see https://github.com/3b/3bmd/pull/50.
You may want to try that fix in the meantime.

**Comment by melisgl** [comment]
This is now fixed in 3b/3bmd.
